### ISSUE TITLE
Find @choice keys in blade files

### ISSUE THREAD

**Issue by Iseldore** [barryvdh/laravel-translation-manager#164]
Hi !

Your package is very usefull and saved me considerable time !

But I'm using `@choice('key', $number) ` in my blade files for pluralization, and they are not recognized by the translation manager.

Any advice ?

Thanks !

**Comment by barryvdh** [comment]
According to this regex: https://github.com/barryvdh/laravel-translation-manager/blob/master/src/Manager.php#L95-L111
It should detect them (as long as key has a dot inside): http://regexr.com/392hu

**Comment by infomax** [comment]
The problem is this part:

"[^\w|>]" .                          // Must not have an alphanum or _ or > before real method

I guess it's because most functions need to be encased in {{}}, but in case of @lang or @choice that's not needed. And if the tpl contains something like this: <h1>@lang('main.title')</h4> it won't match. As soon as you put a space after the <h4> it'll find it. This issue still persists in the latest version. Any chance of modifying the regex to fit these cases? I'm happy to help if you need it :)
Thanks!
