### ISSUE TITLE
translations:find command has some flaws in RegExr.

### ISSUE THREAD

**Issue by qqjt** [barryvdh/laravel-translation-manager#235]
It cannot filter out strings with dots or single quoted strings with semicolons, in blade files for example:
```
<textarea placeholder="{{__("Blabla...")}}"></textarea>
```
```
<input type="text" placeholder="{{__('What\'s up?')}}">
```
Works fine if I remove dots or semicolons in these two cases.

I think something in  `findTranslations()` function located in `src/Manager.php` needs improving, but I don't know how. BTW, I'm using version `0.4.2`.
Have a nice day!

**Comment by mknooihuisen** [comment]
The first point is due to the way Laravel's localization system reads PHP array files (via the format `file.key`).  Putting a space in there somewhere would resolve that example.  My PR #232 addresses this issue somewhat, but the main limiting factor will be Laravel's `file.key` implementation.

The second point is probably due to not escaping the 'single-quote' special character again before putting it in the DB.  I've not tested this one, but that's my guess.
