### ISSUE TITLE
Custom middleware not working

### ISSUE THREAD

**Issue by robertnicjoo** [barryvdh/laravel-translation-manager#297]
Hi,

Based on documentation, if i use default middlewares it's working fine

```php
'route' => [
        'prefix' => 'translations',
        'middleware' => [
	        'web',
	        'auth',
		],
    ],
```

but this has serious issue, **it allows every logged user to have access to translations**.

I have custom middleware named `isAdmin` which it gives access to users with admin roles. But when I try to use this middleware instead of default ones it returns error.

> Any idea how I can use my custom middleware in order to prevent all users having access to translations?

```php
 'middleware' => [
       'isAdmin',
],
```

**Comment by kentdahl** [comment]
Don't you need to append your `isAdmin` middleware instead of replacing? If your `isAdmin` used `Auth::user()` or anything similar, then it won't know you're logged in.

See https://github.com/barryvdh/laravel-translation-manager#laravel--52

Then you should have something like: 

```php
'route' => [
        'prefix' => 'translations',
        'middleware' => [
	        'web',
	        'auth',
	        'isAdmin',
		],
    ],
```

The following works for me (but you might not have the same role system setup) as an example:

```php
       'middleware' => ['web', 'auth', 'role:admin'],
 ```

**Comment by zoldek** [comment]
Hi @robertnicjoo,
try this 
`middleware' => [
	        'web',
	        'auth:isAdmin'
		],`
it's worked for me
