### ISSUE TITLE
array_merge(): Expected parameter 1 to be an array, null given on installation Laravel 7

### ISSUE THREAD

**Issue by chiragsenjaliya** [barryvdh/laravel-translation-manager#364]
ErrorException

  array_merge(): Expected parameter 1 to be an array, null given

  at vendor/barryvdh/laravel-translation-manager/src/routes.php:5
    1| <?php
    2|
    3| declare(strict_types=1);
    4|
    5| $config = array_merge(config('translation-manager.route'), ['namespace' => 'Barryvdh\TranslationManager']);
    6| Route::group($config, function($router)
    7| {
    8|     $router->get('view/{groupKey?}', 'Controller@getView')->where('groupKey', '.*');
    9|     $router->get('/{groupKey?}', 'Controller@getIndex')->where('groupKey', '.*');

**Comment by abdullahessam** [comment]
same here , any solution ?

**Comment by abdullahessam** [comment]
hi @chiragsenjaliya  i found solution but it's not good 
just copy the array from /vendor/barryvdh/laravel-translation-manager/config/translation-manager.php
and place it instead of  config('translation-manager.route') in route.php page and it will work 
then publish the config file then php artisan config:cache 
the undo the the edits in vendor file and it will work perfectly

**Comment by chiragsenjaliya** [comment]
@abdullahessam  best way to doing it to clear bootstrap/cache folder and after then publish config and cache config

**Comment by peterjaap** [comment]
I have this issue as well on my Forge production server. No idea why....

I just replaced the line with array_merge in `routes.php` with;

```php
$config = include(__DIR__ . '/../config/translation-manager.php');
$config = array_merge($config, ['namespace' => 'Barryvdh\TranslationManager']);
```
