### ISSUE TITLE
Delete cancel

### ISSUE THREAD

**Issue by jorenvh** [barryvdh/laravel-translation-manager#69]
When I click the trash icon to delete a translation row in the web interface I get prompted to be sure that I want to delete this item. But when I click cancel the row is delete anyway from the web interface and database. So I have to import all groups again.

When I find the time I will check if I can make a PR. If not you now that there is a small issue.

Thanks for the great packages!

**Comment by andreiculda** [comment]
@jorenvh Yeah there is still an issue here ... As I see the problem is that it uses a data-confirm custom attribute on `<a>` tag. I did not find where this attribute is handled in the code (it's not a standard attribute and is probably handled by bootstrap). You can replace that delete `<a>` tag with your own button and handle action request in `jquery` on the same page.

**Comment by ITDesigns** [comment]
Issue not fixed still.
Workaround that I use is to attach `confirm:complete`event for `a.delete-key` and check for returned answer:
```
  $("a.delete-key").on('confirm:complete', function(e,a){
    event.preventDefault();
    if(a){
      var row = $(this).closest('tr');
      var url = $(this).attr('href');
      var id = row.attr('id');
      $.post( url, {id: id}, function(){
        row.remove();
      });
    }
  });
```
