### ISSUE TITLE
Question: Should my lang files be versioned?

### ISSUE THREAD

**Issue by clemblanco** [barryvdh/laravel-translation-manager#71]
Everything is in the title.
Also isn't it bad to give rw access to my web-user to app/lang (L4.2) on my production box?

**Comment by GregoryClaeyssens** [comment]
I'm asking myself the same question.
My thinking process:
* I think language files should definitely be versioned. Since it is more than likely that you will add some lines to language files in the course of a project.
* On the other hand these language files will probably have been edited by some content administrators, so new translations should not be lost... 

What should word is version your lang files and add the following in you publish script

    php artisan translations:import  // Import new language lines in DB, whithout overwriting current ones in the DB
    php artisan translations:clean // Cleanup (optional)
    php artisan translations:export '*' // Export all your translations back, so you keep the changes made by content managers
