### ISSUE TITLE
Warning Ambiguous class resolution, "CreateTranslationsTable" was found in both...

### ISSUE THREAD

**Issue by jdavidbakr** [barryvdh/laravel-translation-manager#73]
composer dump-autoload is giving me this error

Warning: Ambiguous class resolution, "CreateTranslationsTable" was found in both...

referencing both migration files (the one in my migrations folder plus the one in the vendor folder).  I'm not up on composer enough to figure out how to ignore this via the composer.json file (if indeed I can); I'm sure it's not a dealbreaker but it would be nice to not have the warning every time dump-autoload is run.

**Comment by markwalet** [comment]
Not sure if you can really solve this issue. Same problem in the laravel Spark repo.
The problem is that this published class must have the exact same namespace and name as the non-published version (found in vendor folder)

The only solution for this is replacing the publishable command for an install command.
